version: '3.8'

services:
  contador:
    image: python:3.7-alpine
    container_name: contador
    working_dir: /app
    volumes:
      - ./app.py:/app/app.py
      - ./requirements.txt:/app/requirements.txt
      - ./log.txt:/app/log.txt
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    command: >
      sh -c "apk add --no-cache gcc musl-dev linux-headers curl &&
             pip install -r requirements.txt &&
             flask run > log.txt 2>&1"
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
